necaris/conda.el

conda.el

I was getting an odd error when I was trying to set a conda env from inside of emacs (with ``M-x conda-env-activate``). Somehow, the lambda function here in this defun was being passed "nil" as a value somewhere along the line and failing there, because ``conda--includes-path-element`` assumes that its argument is a string, and fails when called with nil. I tracked it down that far, and making this small change seemed to fix this issue for me. I'm still not entirely sure what was causing it, exactly, but I figured that if it works for me, chances are pretty good that somebody else somewhere has the same issue.

make conda-env-stripped-path a little more robust

---

conda.el

* assume passed buffer name would be first arg in &rest
* Fix activate on windows - do not use "source", and add a newline to
the command
* Replace an ad-do-it with (apply orig-fun...) - seems like advice-add
doesn't provide ad-do-it?

Fix a bug that was breaking shell-strip-env

---

conda.el

I think conda.el should use ["Symbol constituents"](https://www.gnu.org/software/emacs/manual/html_node/elisp/Syntax-Class-Table.html#Syntax-Class-Table) instead of "Word constituents". I have an environment named `hail-ci` and conda.el cannot find said environment due to this. I couldn't figure out the syntax for the symbol constituents class, but `[A-z0-9-]` should work for anyone using ASCII names for their environments. I do not know if `\w` includes other important characters.

Also find environments whose names contain a dash

---

conda.el

On my Ubuntu system, anaconda uses `~/anaconda3` as the default installation directory, while `~/.conda/envs` as the env directory.  I didn't modify the `.condarc` file. So this line probly should change to `conda-env-home-directory`.

fix conda env home

---

conda.el

As done by https://github.com/necaris/conda.el/pull/23 and https://github.com/necaris/conda.el/pull/24 this patch tries to propose a solution to deprecation warnings introduced by latests Conda releases when using cli interface.
W.r.t. https://github.com/necaris/conda.el/pull/23 this proposal does use the same cli command but ignoring stderr.
W.r.t. https://github.com/necaris/conda.el/pull/24 this proposal does not hard-code the warning string to strip out.

Discard stderr on 'conda ..activate' to avoid deprecation warning

---

conda.el

Current regex is quite restrictive as allow only "[A-z0-9-]+" alphanumerical chars plus '-'.
The proposal here is to also accept '_' and '.' : "[A-z0-9-_.]+"

Add '_' and '.' in regex when discovering conda env name from Yml

---

conda.el

This ensures that any subsequent conda commands (e.g. in an `eshell`) are aware of the environment that's been set.
Closes #15

Set CONDA_PREFIX when activating

---

conda.el

The first commit is about the environment location. It was fixed by #20, but seemed to have been reverted accidentally.
The second one is to make the byte compiler a bit happier. Types and groups are specified explicitly for every customization variables.
Thanks for creating and maintaining this package!

Minor fixes

---

conda.el
test/conda-test.el

Two issues fixed:
* The current environment name was missing in the path string of the filter. So
instead of filtering `/path/to/anaconda/envs/env-name/bin` it was
`/path/to/anaconda/envs/bin` and thus no path stripping occured.
* If in the `path-or-path-elements` the path to be stripped ends with an
directory delimiter, no path stripping occured.

Fix path stripping when deactivating an environment

---

conda.el

Addresses #26
When working with many environments it's easy to loose track of all the
environments. One handy solution for this is to have a prefixed environment in
each project's working directory. This commit adds support for these path
prefixed conda environments.
This change also works for environments created by virtualenv.
Details of change:
* Modify `conda-env-stripped-path` so that when a path prefixed environment is
deactivated, `conda-env-current-name` is the path to be stripped. So no
expanseion to `conda-env-default-location` etc. is appropriate.
* `conda-env-deactivate` is only doing something if an environment is
actually activated.
* Introduce `conda-env-is-valid-path`
* Introduce interactive `conda-env-activate-path` which is a modified version
of `conda-env-activate`.

Support for prefixed conda environments

---

conda.el

Fix error when conda-project-env-name is not bound

---

conda.el

I was still having some issues with this function (#52 related). While debugging, I noticed that no error was being thrown when the command failed. This fixes that.
It also sets up the path using `file-name-as-directory` to handle delimiters and such correctly (I haven't tested on windows, but this should work there too).

Add error handling to conda--get-path-prefix, fix path for windows.

---

conda.el

I noticed some problems with the recent changes under windows.
The paths needed to be quoted and conda-env-executables-dir needs to be used instead of "bin".
I've attempted to fix the problems, please review and merge.

Windows compatibility changes in conda--get-path-prefix

---

conda.el

Mostly for clarity so that it's clear what the command being executed by
the system actually is.

Reformat let-bindings in conda--get-path-prefix

---

conda.el

The function `conda-env-activate-path` was using the function
`conda-env-is-valid-path` to check the validity of a conda env. This
function was probably never compatible with Windows since for those
systems `python.exe` lays on the root of the env dir, as in
https://docs.anaconda.com/anaconda/user-guide/tasks/integration/python-path/
This commit fixes this error by using an existing, older function to check the
validity of environments, namely, `conda--env-dir-is-valid`.

Fix #68 `conda-env-activate-path` for Windows

---

conda.el

I use `conda-anaconda-home-tmp` to temporarily save the current value of `conda-anaconda-home` outside `with-current-buffer` block.

Fix #77: buffer local variable `conda-anaconda-home' not working

---

conda.el

Most recent commit missed a paren, so package cannot be loaded

Quickfix for missing paren

---

README.md

Setting the `conda-project-env-name` variable doesn't seem to be valid anymore, but it seems that we can now use `conda-project-env-path` for that. I updated README accordingly.

Document the use of `conda-project-env-path`

---

conda.el

The function `conda-env-shell-init` was not working due to a parenthesis closure issue.
This PR is fixing it.

Fix the function conda-env-shell-init

---

conda.el

Following PR #102 Variable `proper-dir` is undefined which causes the code to break. I've just renamed it to `proper-dir`.
*Note*: I don't know if that is the intended behaviour but at least it prevents the code to break...

Rename undefined variable `proper-dir` to `envs-dir`

---

conda.el

This path is used everywhere at work, that would be awesome if you accept to add it to the default list!

Add ~/.conda path to conda-home-candidates

---

conda.el

Committed too soon -- `deactivate`, unlike `activate`, doesn't take arguments. Closes #118

Fix deactivating environments

---

conda.el

Also, read the `envs_dirs` from the configuration by default, rather than hard-coding assumptions about `conda-anaconda-home`.
Closes #119

Add ability to read `.condarc`

---

conda.el

May help debug #130, but is good to have around in general

Add error handling if Conda's response is not expected

---

conda.el

Emacs 28 as installed from conda-forge does not have native json support yet (see https://github.com/conda-forge/emacs-feedstock/issues/59), so it seems more solid to check whether `json-parse-string` is available rather than the emacs version.

fix: check if json-parse-string available (instead of emacs version)

---

conda.el

Emacs 28.1 gives a lot of warnings from this package on start up about docstrings. This should help clear those up

Fixed style issues reported by checkdoc-minor-mode

---

conda.el

In a few cases, e.g., when opening a ipynb notebook via `code-cells`, `buffer-file-name` will return nil but the working directory can still obtained via the `default-directory` variable.

feat: try `default-directory` to infer env when `filename` is nil

---

conda.el

This fix the initial stringp nil error, when:
1. Anaconda is not added to Path.
2. Anaconda Home is set to the directory where conda.exe installed.

fix autoload for windows

---

conda.el

https://github.com/doomemacs/doomemacs/issues/6658
This is the similar that I'm facing , Here is the fix for this.
On my system conda--get-executable-path retruns: "c:/Users/Anudeep Kumar/miniconda3/Scripts/conda.exe"
The problem with the previous code is that doesn't work for the username that contains space in it.
The fix is to simply add double-quotes around that path before trying to run the version command.
Thanks to @tdhock for helping me find the solution.

Quote Conda command

---

conda.el

Borrowed from Doom Emacs' fix in https://github.com/doomemacs/doomemacs/commit/8f60a1bc46b3b1ef7987aa85764f35ee2249721d

fix: Handle nonexistence of `conda-home-candidates`

---

conda.el

To ensure cached config is refreshed. Closes #134

Add `conda-reload-config` helper

---

conda.el

Fixes #154. Simplifies `conda--get-version` to a) stop using a shell, and b) discard stderr, so we don't try to parse any diagnostic messages as a version.

fix: Ignore stderr when getting version

---

conda.el

Fixes #163. Discards the standard error from the `conda` command, ensuring that it _should_ be more consistently parseable as JSON.

fix: Refactor `conda--call-json` to ignore stderr

---

conda.el

I've raised [this PR](https://github.com/necaris/conda.el/pull/168) earlier, but decided to pull it to make a few refinements. This is the real PR!
-   fixed [issue](https://github.com/necaris/conda.el/issues/35) about missing require `em-dir` declaration
-   recognise both `yml` and `yaml` extensions for environment files (issue [here](https://github.com/necaris/conda.el/issues/158))
-   changed references to YML in function/variable names and docstrings
-   updated formatting of messages referencing environment names
-   added buffer-local configuration options `conda-env-yaml-base-name` and `conda-pip-requirements-filename` to change expected environment filenames.
-   If such file exists in parent hierarchy anywhere, then open it
-   If such file does not exist, then generate new file …

Pack of fixes / new features
