necaris/conda.el

conda.el

Add custom setting for verbosity on switching environments

---

conda.el

Add needed paths for Windows

---

README.md

PS: thanks for this developing this package!

fix markdown formatting for readme

---

conda.el

This is pretty simple, but there is a bug in the code for automatically detecting environment.yml files.

Fixing a bug in the detection of "environment.yml" files

---

conda.el

use full path for conda

---

README.md

See https://github.com/necaris/conda.el/issues/51#issuecomment-621961455

Add note to README about conda-env-subdirectory setting

---

conda.el

The `conda-env-current-name` was being used for storing both path and
name of environments, depending on whether it was being called by
`conda-env-activate` or `conda-env-activate-path`.
This commit removes this ambiguity, and also removes duplicate code that
become unnecessary after the simplication.
Moreover, this commit fixes an existing bug (described in #47) where the package was unable
to deactivate a base environment set with the hack
`(conda-env-activate "..")`.

Refactor current-name -> current-path

---

conda.el

This commit fixes #47 by handling the 'base' environment, which should
always be present in a conda installation and correspond to the location
of the Anaconda installation.

Fix #47 handle 'base' env

---

conda.el

The variable `conda-env-current-name` has been removed in a recent
refactoring due to it being no longer necessary for operational purposes
of the package. Also, it had an ambiguous use and thus the reason for
the previous removal, see 5dc78b5.
However, now I realize it is important for having a nicer interface when
activating a conda environment, running `conda-env-shell-init`,
displaying env name in the modeline. This commit restores this variable
and associated functionality.

Fix #69 conda-env-current-name undefined

---

conda.el

Replace the previous "source activate" with "conda activate" -- see #54  
----
#

Update activation command, auto-format

---

conda.el

This seems to work better for me when using `conda-env-autoactivate-mode`.

pop-to-buffer seems to work better for me

---

conda.el

Fix missing close paren

---

conda.el

Close https://github.com/necaris/conda.el/issues/83 .
Would be great if someone else can help test it.  I'm using bash and don't have other shells available at the moment.

Fix command quote.

---

conda.el

This change seems to have been lost

reapply switch-to-buffer -> pop-to-buffer change

---

README.md
conda.el

go back to switch-to-buffer, after discussing with wtianyi in #93, but adding a note to README about a possible workaround.

go back to switch-to-buffer, after discussing with wtianyi in #93

---

conda.el

Refactor checks for conda env validity to include the `conda-meta` directory. Closes #101

Allow activating empty conda envs

---

conda.el

Closes #35. Uses the proof-of-concept code as the implementation.

Add an eshell prompt function

---

conda.el

Fixes broken conda environment (de)activation on Windows. Tested under Windows 10. Asks for correct JSON data, `conda shell.cmd.exe+json`, and splits PATH with `;` instead of `:`.

fix conda json (de)activation on Windows

---

conda.el

Fix `prev-env` variable

---

conda.el

Fix the broken `conda--version>=` comparison function, which should
correctly trigger JSON-format activation for newer Conda versions. Also
make a few other cleanups to make this code path clearer and more reliable. Closes #116.

Fix activation on Conda >= 4.13

---

conda.el

Refactor `conda--call-json-subcommand` to use `process-file` rather than
the `shell-command-to-string` wrapper. This also lets us add arbitrary
arguments after the subcommand, rather than just an optional `env-dir`.
Closes #118 (again)

Allow arbitrary arguments to call-json-subcommand

---

conda.el

Update copyright year, remove unnecessary NIH function

Updates and cleanups

---

conda.el

Add option to always activate "base" environment by default

---

conda.el

Fix the `"No Conda environment found for nil" after #140.

fix: working dir from filename (preference) or default-directory

---

README.md
conda-projectile.el
conda.el

Add a basic mode line same as the doc.
Add a mode-line that mix with projectile project name.

Add mode line
